### PR TITLE
Update 03-visual-studio-code.html.md

### PR DESCRIPTION
**Pull request by LeeRitholtz**
Small update for new menu organization in VSCode.

### CODE REVIEW

**Comment by Gama11** [comment]
Seems correct to me?

**Comment by LeeRitholtz** [comment]
Interesting - Looks like a difference in VSCode for macOS vs. Windows.

screen shot 2018-07-23 at 2 00 54 pm

**Comment by Gama11** [comment]
Mabye we should just change the instructions to go through the command palette (F1 -> search for keyboard), that's more convenient anyway. :)

**Comment by Gama11** [comment]
Then again, a bit earlier, we mention `File` -> `Open Folder` too... :/ So perhaps it's best to just leave it as-is.

**Pull request closed without merging**
