### PR TITLE
Add an Community Tutorials section to Resources

### PR DESCRIPTION
**Pull request by ninjamuffin99**
draft PR for now, relevant issue #273 

In here and/or the issues post, if we can collect a few tutorials to add, can get this one rolling and published 

Feel free to let me know on any notes related to how to FORMAT the list of things (how many ### for headings, link format, etc.)

Felt like "community tutorials" was the best description

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
ohsat has a handful of tutorials on their site: https://www.ohsat.com/tutorial/#haxeflixel-tutorials

I wonder how LOOSE we want to format the list. Do we list each tutorial individually, under it's own little `oshat tutorials` section

```md
- [oshat tutorials](https://www.ohsat.com/tutorial/#haxeflixel-tutorials)
  - [HaxeFlixel crash course
](https://www.ohsat.com/tutorial/flixel/hf-pong/)
  - [Pixel Perfect 2D water shader
](https://www.ohsat.com/tutorial/flixel/pixel-perfect-water-shader/)
<!-- etc. etc.... -->
```
turns to something like:

- [oshat tutorials](https://www.ohsat.com/tutorial/#haxeflixel-tutorials)
  - [HaxeFlixel crash course
](https://www.ohsat.com/tutorial/flixel/hf-pong/)
  - [Pixel Perfect 2D water shader
](https://www.ohsat.com/tutorial/flixel/pixel-perfect-water-shader/)

**Comment by SeiferTim** [comment]
Are these worthy of inclusion?

https://www.youtube.com/playlist?list=PL0mTR4YHxhDhD39potymkrbI44DzwTyi8

**Comment by ninjamuffin99** [comment]
> Are these worthy of inclusion?
> 
> https://www.youtube.com/playlist?list=PL0mTR4YHxhDhD39potymkrbI44DzwTyi8

nice yeah I'd say so 🙂

**Comment by SeiferTim** [comment]
Sorry I just remembered another one:

https://axolstudio.com/articles/2023-07-23-tims-tips-1-texture-packing-sprites/

**Comment by ninjamuffin99** [comment]
ooh nice nice! I will add these both

**Pull request merged**
