### PR TITLE
Minor fixes to tutorial, should resolve issues #89, #119, and #120 #123

### PR DESCRIPTION
**Pull request by SeiferTim**
Now with fewer merge conflicts!

### CODE REVIEW

**Comment by Gama11** [comment]
Doesn't look like that fixed it.

Before:



Now:

**Comment by Gama11** [comment]
Also, what about the `checkEnemyVision()` thing mentioned by #120?

**Comment by SeiferTim** [comment]
Markdown is arbitrarily changing underscores and double-underscores into `<em>` and `<strong>` sometimes, and there doesn't seem to be any way to disable it. I tested out my 'fixes' in a Markdown editor, and they worked, but I have no idea what's going on with the site... 
Markdown should really not be used on these tutorial pages... 

With #120 , there is no loop in `checkEnemyVision`, I discussed the function in [Part VIII](http://haxeflixel.com/documentation/part-viii-enemies-and-basic-ai/) and it's exactly as it should be.

**Comment by Gama11** [comment]
Probably not a good idea to mix markdown with html. ;)

Guess we can at least close that issue then...

**Pull request merged**
